version: "3.8"
services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8080 --reload 
    depends_on:
      - neo4j
    env_file:
      - .env



  neo4j:
    image: neo4j:enterprise # Neo4j Enterprise Edition 사용
    ports:
      - "7474:7474" # Neo4j HTTP 포트
      - "7687:7687" # Neo4j Bolt 포트
    volumes:
      - neo4j-data:/data
      - neo4j-logs:/logs
    environment:
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
      NEO4J_PLUGINS: '["apoc"]'
      NEO4J_AUTH: "${NEO4J_USER}/${NEO4J_PASSWORD}"

volumes:
  neo4j-data:
  neo4j-logs:
